let data = [
    { name: "Australia", selected: false },
    { name: "Brazil", selected: false },
    { name: "Canada", selected: false },
    { name: "Denmark", selected: false },
    { name: "Egypt", selected: false },
    { name: "France", selected: false },
    { name: "Germany", selected: false },
    { name: "Hungary", selected: false },
    { name: "India", selected: false },
    { name: "Japan", selected: false },
    { name: "Kenya", selected: false },
    { name: "Luxembourg", selected: false },
    { name: "Mexico", selected: false },
    { name: "Netherlands", selected: false },
    { name: "Oman", selected: false },
    { name: "Peru", selected: false },
    { name: "Qatar", selected: false },
    { name: "Russia", selected: false },
    { name: "Spain", selected: false },
    { name: "Thailand", selected: false },
    { name: "United Kingdom", selected: false },
    { name: "Vietnam", selected: false },
    { name: "Italy", selected: false },
    { name: "United States", selected: false },
    { name: "China", selected: false },
    { name: "South Africa", selected: false },
    { name: "New Zealand", selected: false },
    { name: "Argentina", selected: false },
    { name: "Belgium", selected: false },
    { name: "Chile", selected: false },
];



export default data;